finishing up

diff --git a/bin/S99pppwn-service b/bin/S99pppwn-service
--- a/bin/S99pppwn-service
+++ b/bin/S99pppwn-service
@@ -49,21 +49,57 @@ reset_interface() {
 kill_services() {
 	#Stop pppoe server, nginx, php-fpm and any running pppwn
 	printf "Stopping services... "
-	SERVICE_PIDS=`pidof pppoe-server php-fpm nginx pppwn1 pppwn2 pppwn3`
+	SERVICE_PIDS=`pidof pppoe pppoe-server php-fpm nginx pppwn1 pppwn2 pppwn3`
 	[ "$SERVICE_PIDS" != "" ] && (kill -9 $SERVICE_PIDS && echo "OK" || echo "FAIL") || echo "NOT RUNNING"
 }
 
 execute_pppwn() {
+    # We don't know what's running so we stop everything
 	stop
+    # Start PPPoE server and wait for connection (max 10 attempts)
+    # This improves the chances of the exploit working. In my case, it went from unstable
+    # (between 1 to 10 attempts) to 100% success rate at first shot when coupled with
+    # CORRUPT_NUM=10 for a stubborn 9.60.
+    start_pppoe
+    wait_for_pppoe
+    stop
 	$CMD
 	restart_services
 }
 
+start_pppoe() {
+    printf "Starting PPPoE server... "
+	pppoe-server -I eth0 -T 60 -N 1 -C isp -S isp -L 10.1.1.1 -R 10.1.1.2 &
+	[ $? = 0 ] && echo "OK" || echo "FAIL"
+}
+
+wait_for_pppoe() {
+    IP="10.1.1.2"
+    MAX_ATTEMPTS=10  # Maximum number of iterations
+
+    printf "Waiting for $IP to be reachable"
+    attempts=0
+    while [ $attempts -lt $MAX_ATTEMPTS ]; do
+        printf "."
+        sleep 1
+
+        if ping -c 1 -W 1 $IP >/dev/null 2>&1; then
+            echo " Reachable!"
+            break
+        fi
+
+        attempts=$((attempts + 1))
+
+        if [ $attempts -ge $MAX_ATTEMPTS ]; then
+            echo " Max attempts reached. $IP is still unreachable."
+            break
+        fi
+    done
+}
+
 start_services() {
 	# Start PPPoE server, nginx, php-fpm
-	printf "Starting PPPoE server... "
-	[ $? = 0 ] && echo "OK" || echo "FAIL"
-	pppoe-server -I eth0 -T 60 -N 1 -C isp -S isp -L 10.1.1.1 -R 10.1.1.2 &
+	start_pppoe
 	/etc/init.d/S50nginx start
 	/etc/init.d/S49php-fpm start
 	printf "Starting Web monitor... "
